### ISSUE TITLE
INTERNAL SERVER ERROR while downloading the training dataset 

### ISSUE THREAD

**Issue by Sakethsreeram7** [monajemi-arman/dental_decay_detection#1]
--2024-05-14 17:17:28--  https://bitewing.monajemi.ir/3.ckpt
Resolving bitewing.monajemi.ir (bitewing.monajemi.ir)... 87.248.155.33
Connecting to bitewing.monajemi.ir (bitewing.monajemi.ir)|87.248.155.33|:443... connected.
HTTP request sent, awaiting response... 500 INTERNAL SERVER ERROR
2024-05-14 17:17:29 ERROR 500: INTERNAL SERVER ERROR.

when running this command : **wget https://bitewing.monajemi.ir/3.ckpt**

**Comment by monajemi-arman** [comment]
It was an error in the flask code I wrote. It is now fixed.
